name: Deploy
on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
    branches:
      - main
  
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up JDK 11
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: 11
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
          distribution: 'temurin'

      - name: Customize the Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@7c60eb95b2d5ec18f2e0e29f34c9ed69475e7a96 # v21
        with:
          servers: '[{ "id": "ossrh", "username": "${{ secrets.SONATYPE_USERNAME }}", "password": "${{ secrets.SONATYPE_PASSWORD }}" }, { "id": "ossrh", "username": "${{ secrets.SONATYPE_USERNAME }}", "password": "${{ secrets.SONATYPE_PASSWORD }}" }]'

      - name: Configure the application
        run: |
          properties="src/main/resources/application.properties"
          rm -f "${properties}"
          echo "secret_server.tenant = ${{ secrets.TSS_TENANT }}" >> "${properties}"
          echo "secret_server.oauth2.username = ${{ secrets.TSS_USERNAME }}" >> "${properties}"
          echo "secret_server.oauth2.password = ${{ secrets.TSS_PASSWORD }}" >> "${properties}"
          echo "secret.id = ${{ secrets.TSS_SECRET_ID }}" >> "${properties}"

      - name: Deploy with Maven
        run: |
          mvn -P github -B -C -ff -ntp -U deploy -Dregistry=https://maven.pkg.github.com/delineaXPM -Dtoken=GH_TOKEN -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
