name: Deploy
on:
  push:
    # Trigger publish when pushing version tags like v1.2.3, v2.0, etc.
    tags:
      - "v*"
  
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          distribution: 'temurin'
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Customize the Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
           servers: '[{ "id": "ossrh", "username": "${{ secrets.SONATYPE_USERNAME }}", "password": "${{ secrets.SONATYPE_PASSWORD }}" }]'

      - name: Configure the application
        run: |
          properties="src/main/resources/application.properties"
          rm -f "${properties}"
          echo "secret_server.tenant = ${{ secrets.TSS_TENANT }}" >> "${properties}"
          echo "secret_server.oauth2.username = ${{ secrets.TSS_USERNAME }}" >> "${properties}"
          echo "secret_server.oauth2.password = ${{ secrets.TSS_PASSWORD }}" >> "${properties}"
          echo "secret.id = ${{ secrets.TSS_SECRET_ID }}" >> "${properties}"

      - name: Deploy with Maven
        run: |
          mvn -P sonatypeDeploy -B -ntp clean deploy
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
